// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.as.cert.domain;

import com.as.cert.domain.CourseDetail;

privileged aspect CourseDetail_Roo_JavaBean {
    
    public String CourseDetail.getName() {
        return this.name;
    }
    
    public void CourseDetail.setName(String name) {
        this.name = name;
    }
    
}
