// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.as.cert.domain;

import com.as.cert.domain.TrainingProgramIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TrainingProgramIntegrationTest_Roo_Configurable {
    
    declare @type: TrainingProgramIntegrationTest: @Configurable;
    
}
